### ISSUE TITLE
Does not work (anymore) with MiniNet 2.2.1

### ISSUE THREAD

**Issue by alexvoss** [named-data/mini-ndn#11]
Hi, 

recent changes have broken Mini-NDN for people using MiniNet 2.2.1 (e.g., in Ubuntu 16.4.2 and 16.10). The offending line is this:

--8<--
  File "/usr/local/lib/python2.7/dist-packages/Mini_NDN-0.3.0-py2.7.egg/ndn/remote_ndn_link.py", line 62, in <module>
    from mininet.examples.cluster import RemoteLink, RemoteGRELink
ImportError: cannot import name RemoteGRELink
--8<--

RemoteGRELink was added to MiniNet relatively recently. As this seems to be for some optional functionality, would it be possible to use it only if the underlying MiniNet supports it? I.e.: place try/catch clauses around the import and other code to avoid runtime errors like the above?

Cheers,

Alex

**Comment by agawande** [comment]
Yes seems like a good idea. You can open an issue (https://redmine.named-data.net/projects/mini-ndn) and submit a patch if you like: https://gerrit.named-data.net.
Otherwise I will try to submit one soon.

**Comment by alexvoss** [comment]
Thanks for the prompt reply. I am no Python wizard as you can probably tell by my temporary fix in ndn/remote_ndn_link.py:

--8<--
from mininet.examples.cluster import RemoteLink
try:
    from mininet.examples.cluster import RemoteGRELink
except ImportError:
    class RemoteGRELink:
        pass
--8<--

There must be a more elegant way of dealing with the ImportError but it seems fine for me just now as it takes me to what I assume is the next problem:

--8<--
nfd.conf or nfd.conf.sample cannot be found in the expected directory. Exit.
--8<--

Cheers,
Alex

**Comment by agawande** [comment]
Have you installed NFD (sudo ./waf install)? Then there should be a file at /usr/local/etc/ndn/nfd.conf.sample

**Comment by alexvoss** [comment]
I have nfd and the other ndn packages but I am lazy and installing from the PPA. It seems that nfd.conf.sample is at: /etc/ndn/nfd.conf.sample - I will create a synlink for now but it would be great if you could change the code to add this as an alternative path?

**Comment by agawande** [comment]
Okay, let me know if the symlink works - then I will add this as an alternative path too.

**Comment by alexvoss** [comment]
ln -s /etc/ndn /usr/local/etc      # seems to do the trick, the install verification is running

**Comment by agawande** [comment]
Okay thanks for reporting, I have filed the issues and will try to push changes when I get some time:
https://redmine.named-data.net/issues/3993
https://redmine.named-data.net/issues/3992

**Comment by alexvoss** [comment]
Thanks very much for the prompt help!

**Comment by alexvoss** [comment]
Hi,

sorry to trouble you again. I seem to be having [this problem](https://github.com/mininet/mininet/issues/629) with Mininet as installed by Ubunty 16.04. In the end, it would seem like the best advice to give to people is to install Mininet from source. As far as I can tell, this is a problem that does not have a workaround given the version in the Ubuntu repositories. So, instead of patching the Mini-NDN source code, I would change the [installation instructions](https://github.com/named-data/mini-ndn/blob/master/INSTALL.md).

Cheers,

Alex

**Comment by agawande** [comment]
Yes, the latest version of Mininet does not have that problem. I can put a line in our installing instructions that mininet needs to be installed from source in Ubuntu 16+
