### ISSUE TITLE
libChronoSys.so not found after installation

### ISSUE THREAD

**Issue by maufl** [named-data/mini-ndn#13]
Hi, I installed mini-ndn using the script. I also installed all dependencies using the script. However, I had one remaining issue on Ubuntu 14.04. When I ran `nlsrc` it failed because it did not find `libChronoSys.so`. While it was installed, it was not picked up until I ran `ldconfig`. You might want to add this command to the install script after `libChronoSys` is installed.

**Comment by agawande** [comment]
Thanks, filed an issue: https://redmine.named-data.net/issues/4295
