### ISSUE TITLE
GNU nano?

### ISSUE THREAD

**Issue by xuanvl95** [named-data/mini-ndn#14]
Can you send me file txt of ndn-cxx , NFD , ChornoSync checkout code

**Comment by agawande** [comment]
ndn-cxx: b555b00c280b9c9ed46f24a1fbebc73b720601af
NFD: f4056d0242536f85b7d7b4de1b5ac50dad65c233
Chronosync: 097bb448f46b8bd9a5c1f431e824f8f6a169b650

**Comment by xuanvl95** [comment]
Thank you, agawande!!!
