### ISSUE TITLE
NDN report

### ISSUE THREAD

**Issue by xuanvl95** [named-data/mini-ndn#17]
Hi, Excuseme ... I have a NDN report  operation , can you write the details of the operation of NDN like  your video "Mini-NDN". I like your video, but I'm trying to understand what you do. Thank you so much!

**Comment by agawande** [comment]
I don't understand what you mean by "NDN report operation" and "details of the operation of NDN"?

**Comment by xuanvl95** [comment]
Sorry ... A report about Named Data Networking like this video you demo

**Comment by agawande** [comment]
I won't have time to make a video/report for that. You can take a look at:
https://named-data.net/publications/
https://named-data.net/publications/tutorials/

**Comment by xuanvl95** [comment]
Thank you!!. Can you explain when you ping "ndnping -c5 /ndn/b-site/b. What is -c5 mean?

**Comment by agawande** [comment]
Please read manpage:
man ndnping
Same for any other application/tool

**Comment by xuanvl95** [comment]
Thank you !
