### ISSUE TITLE
NDN topology

### ISSUE THREAD

**Issue by xuanvl95** [named-data/mini-ndn#18]

**Comment by xuanvl95** [comment]
![unnamed](https://user-images.githubusercontent.com/32503779/31261231-1a9e8d62-aa7d-11e7-9675-3c0ebc8c8149.png)

It's NDN topology right?

**Comment by xuanvl95** [comment]
Hello! I'm have a question, when you start minindn why only controller , node a, node b start but SWITCHES not start?

**Comment by agawande** [comment]
Mini-NDN does not support switches in the conf. You can try to manually add it to the topology in the code (Look at Mininet examples).

**Comment by masfiyan** [comment]
> ![unnamed](https://user-images.githubusercontent.com/32503779/31261231-1a9e8d62-aa7d-11e7-9675-3c0ebc8c8149.png)
> 
> It's NDN topology right?

@xuanvl95 Sir can you please tell me that, how can I create NDN topology ?? from it's GUI, is MINI-NDN have another version ?? in which from GUI I can create it's topology
