### ISSUE TITLE
ndnping site a

### ISSUE THREAD

**Issue by xuanvl95** [named-data/mini-ndn#19]
Why I can't use ndnping /ndn/a-site/a

**Comment by agawande** [comment]
You need to give more details about how you are trying it.

**Comment by xuanvl95** [comment]
It mean the first time you use ndnping and ndnpingserver to communica with two node, and then you choose Experiments, and I don't understand "/tmp/b/ndnping.txt " and "/tmp/arizona/ping-data/caida.txt".
I don't understand ".txt" you use. Why didn't you use "ndnping" ?

**Comment by agawande** [comment]
That is just the name of the file where I store the ndnping logs. I use the node name there because it has the logs of the ping which the node arizona sent to node caida.

**Comment by xuanvl95** [comment]
I understand.. but can it use ndnping?

**Comment by agawande** [comment]
Yes. Something like this should work:
mini-ndn> b ndnping -c3 /ndn/a-site/a
(Your topology has to have the nodes named a and b).
or
mini-ndn> arizona ndnping -c30 /ndn/caida-site/caida &> caida.logs &

**Comment by xuanvl95** [comment]
mini-ndn> b ndnping -c3 /ndn/a-site/a
PING /ndn/a-site/a
nack from /ndn/a-site/a: seq=6916386128701697211 time=26.6781 ms reason=NoRoute
nack from /ndn/a-site/a: seq=6916386128701697212 time=22.004 ms reason=NoRoute
nack from /ndn/a-site/a: seq=6916386128701697213 time=21.8288 ms reason=NoRoute

**Comment by xuanvl95** [comment]
mini-ndn> arizona ndnping -c30 /ndn/caida-site/caida &> caida.logs &
*** Unknown command: arizona ndnping -c30 /ndn/caida-site/caida &> caida.logs &

**Comment by agawande** [comment]
In default topology there is no node named arizona.
What is the output of b nfdc fib?

**Comment by xuanvl95** [comment]
mini-ndn> b nfdc fib
FIB:
  /localhop/ndn/NLSR/LSA/b-site/%C1.Router/cs/b/adjacency nexthops={faceid=259 (cost=0)}
  /localhost/nfd/rib nexthops={faceid=256 (cost=0)}
  /localhop/ndn/NLSR/LSA/b-site/%C1.Router/cs/b nexthops={faceid=259 (cost=0)}
  /ndn/a-site/%C1.Router/cs/a nexthops={faceid=257 (cost=10)}
  /ndn/a-site/a nexthops={faceid=257 (cost=10)}
  /ndn/broadcast/KEYS nexthops={faceid=259 (cost=0), faceid=257 (cost=10)}
  /ndn/b-site/%C1.Router/cs/b nexthops={faceid=259 (cost=0)}
  /localhop/ndn/NLSR/LSA nexthops={faceid=257 (cost=10)}
  /localhost/nfd nexthops={faceid=1 (cost=0)}
  /localhop/ndn/NLSR/LSA/b-site/%C1.Router/cs/b/name nexthops={faceid=259 (cost=0)}
  /localhop/ndn/NLSR/sync nexthops={faceid=259 (cost=0), faceid=257 (cost=10)}
  /localhost/nlsr nexthops={faceid=259 (cost=0)}

**Comment by agawande** [comment]
Are you running an ndnpingserver on node a, something like:
mini-ndn> a ndnpingserver /ndn/a-site/a &> /dev/null &
? This will listen on that prefix and answer ndnping.

**Comment by xuanvl95** [comment]
Thank man! it work

**Comment by xuanvl95** [comment]
/ndn/a-site/a --> it's controller ?

**Comment by agawande** [comment]
Not sure what you mean by "it's controller"?

**Comment by xuanvl95** [comment]
/ndn/a-site/a  -> what does it mean ?

**Comment by agawande** [comment]
It is an NDN name which router a advertises to other routers on the network.

**Comment by xuanvl95** [comment]
Are you use facebook, I have a alot of questions to ask you.

**Comment by agawande** [comment]
I think here or on the mailing list (http://www.lists.cs.ucla.edu/mailman/listinfo/mini-ndn) is better so that others can benefit.

**Comment by xuanvl95** [comment]
The last question is /ndn/caida-site/caida , cab it ping with arizora : arizona ndnping -c 3 /ndn/caida-site/caida

**Comment by agawande** [comment]
You need to use the ucla or caida topology which has the arizona node:
sudo minindn ndn_utils/topologies/minindn.ucla.conf

**Comment by xuanvl95** [comment]
mini-ndn> ndn_utils/topologies/minindn.ucla.conf
*** Unknown command: ndn_utils/topologies/minindn.ucla.conf

**Comment by xuanvl95** [comment]
Can you hep me Demonstrate NDN transmission environment to be able to demo and apply to routing in a basic network consists of three areas: DMZ server, Access LAN and Internet (also create a server containing Internet services simulator) . Then the PC in the LAN can access DMZ services and access the Internet

**Comment by agawande** [comment]
Just use "sudo minindn ndn_utils/topologies/minindn.ucla.conf" (without quotes) to run Mini-NDN with the topology that has the arizona node which you can access as you did with node "b" once minindn comes up. Don't use the command in already started Mini-NDN!

For demonstrating NDN transmission environment, you will have to implement your own design. (I am not sure how to accomplish all your requirements).
It should be more rewarding and satisfying if you do it by yourself :) and you can learn so much!

I am sorry, but I only have the time to answer a few well-thought specific questions.

**Comment by xuanvl95** [comment]
Thank you very much.

**Comment by xuanvl95** [comment]
The last question can you answer : How can NDN creat a web server

**Comment by agawande** [comment]
Not sure how to do that. I found this on the mailing list:
http://www.lists.cs.ucla.edu/pipermail/ndn-interest/2017-April/001674.html
(Maybe look into ndn-js: https://github.com/named-data/ndn-js?)
