### ISSUE TITLE
Error when verify mini-ndn installation

### ISSUE THREAD

**Issue by Imendh** [named-data/mini-ndn#24]
Hi,
After the installation  of mini-ndn, in the verification step using this command:
sudo minindn --experiment=pingall --nPings=50
I got the following error:
Traceback (most recent call last):
  File "/usr/local/bin/minindn", line 5, in <module>
    pkg_resources.run_script('Mini-NDN==0.3.0', 'minindn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Mini_NDN-0.3.0-py2.7.egg/EGG-INFO/scripts/minindn", line 67, in <module>
    from mininet.examples.cluster import MininetCluster, RoundRobinPlacer, ClusterCleanup
ImportError: No module named cluster
 
Thank you in advance. 

Imen

**Comment by agawande** [comment]
Hi, please use the latest Mininet (install from source as mentioned here: https://github.com/named-data/mini-ndn/blob/master/INSTALL.md#installing-mininet).
(Relevant issue: https://github.com/named-data/mini-ndn/issues/11)

**Comment by Imendh** [comment]
Hi, 
Thank you for your response.
I use the latest version of Mininet installed from the source using:
git clone --depth 1 https://github.com/mininet/mininet.git
But, I'm working with ubuntu 14.04 LTS. Is this error because of ubuntu version??

**Comment by agawande** [comment]
Ubuntu 14.04 LTS should work. What is the output of:
sudo mn --version
and
sudo mn
?

**Comment by Imendh** [comment]
This is the output:

gmi@gmi-X551CA:~/mini-ndn$ sudo mn --version
[sudo] password for gmi: 
2.3.0d1
gmi@gmi-X551CA:~/mini-ndn$ sudo mn
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet>

**Comment by agawande** [comment]
Hmm, those are correct.
Did you install Mininet from apt-get earlier then you can try purging it to make sure there is no conflict.
And then try to see if it works in python prompt:
$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mininet.examples.cluster import MininetCluster
>>>

**Comment by Imendh** [comment]
It works know very well after apt-get remove mininet and reinstalling mini-ndn.
Thank you for your response.
