### ISSUE TITLE
NFD error

### ISSUE THREAD

**Issue by iamxg** [named-data/mini-ndn#25]
Hi Ashlesh,
Good morning!
Could you tell me where this problem may come from?
![image](https://user-images.githubusercontent.com/30093996/34886069-8f09e898-f787-11e7-9de0-d5d68ea3475b.png)

**Comment by agawande** [comment]
Not sure, what is face 258 (in sta3 nfdc face)?

**Comment by iamxg** [comment]
I  find that I only can run nfd by using the command "sudo nfd" rather than "nfd".

**Comment by agawande** [comment]
You mean sudo nfdc right (not nfd) ? Hmm, not sure why that is.

**Comment by iamxg** [comment]
![image](https://user-images.githubusercontent.com/30093996/34894124-b7c570c2-f7a5-11e7-8ae8-47216c419632.png)

**Comment by iamxg** [comment]
I use "sudo ./install.sh -a " command in mini-ndn.

**Comment by agawande** [comment]
Okay you do need sudo to run NFD
(https://named-data.net/doc/NFD/current/FAQ.html#how-to-run-nfd-as-non-root-user)

**Comment by iamxg** [comment]
Ok, I try it. Thanks a lot!
