### ISSUE TITLE
help!!  when I install mini-ndn v0.1.1,I got a error.

### ISSUE THREAD

**Issue by zhangdongdongdong** [named-data/mini-ndn#27]
my step is as follows:
(1) git clone -b v0.1.1 https://github.com/named-data/mini-ndn/     ,I need to install the version 0.1.1
(2)cd mini-ndn
(3)sudo ./install.sh -mrfti

when i do the third step,some error occur:

cp: can't get"ndn_utils/client.conf.sample"  file status(stat): no such file or directory
cp: can't get"ndn_utils/nlsr.conf"  file status(stat): no such file or directory
cp: can't get"ndn_utils/topologies/default-topology.conf" file status(stat): no such file or directory
cp: can't get "ndn_utils/topologies/minindn.testbed.conf"  file status(stat): no such file or directory
python: can't open file 'setup.py': [Errno 2] No such file or directory

please help me fix this problem,thank you.

**Comment by agawande** [comment]
What does git log -1 say?

Also why do you want to checkout such an old version? You will need the correct older versions of ndn-cxx, NFD, NLSR, ndn-tools to run mini-ndn.

**Comment by dongdongdongZhang** [comment]
Hi,agawande.
I check out the release date of mini-ndn v0.1.1,mininet,NFD,NLSR,ndn-cxx,ndn-tools,and I found the release date of the following version is very close:
Mini-ndn v0..1.1 ----release time: 2015年11月 4号
Mininet v2.2.1  ----release time:2015-4-5
NFD v0.4.0-beta2 ----release time:2015-10-23
NFD v0.4.0-beta1 ----release time:2015-10-23
Ndn-cxx	v0.4.0-beta2 ----release time:2015-10-22
Ndn-cxx v0.4.0-beta1  ----release time:2015-10-22
NLSR v0.2.1 ----release time:2015-6-30
Ndn-tools v0.2 ----release time:2015-8-31
But I'm not sure this method is correct or not? Can you help me to solve this problem.

**Comment by dongdongdongZhang** [comment]
Hi,agawande .
Fortunately , I installed mini-ndn v0.1.1 successfully and NDN.p4 is also worked. I list the correct version of all dependencies:
 NFD v0.3.4
 NLSR v0.2.1
 ndn-cxx 0.3.4
 ndn-tools v0.2
 mininet v2.2.1
I install all dependencies manually,and use: sudo ./install.sh -i to install mini-ndn v0.1.1.
Also I will try the latest mini-ndn later.
Thanks for your help, Sincerely!
