### ISSUE TITLE
question about NLSR

### ISSUE THREAD

**Issue by whiteysy** [named-data/mini-ndn#28]
Hi, i want to know if there is any tool for NLSR in mini-ndn to get some informations about the entire work process of NLSR, such as neighbor finding, route table calculation, lsdb updates and so on. Look forward to your kind reply.

**Comment by agawande** [comment]
Yes there is nlsrc:
mini-ndn> a nlsrc status

Also check nlsr log:
/tmp/a/minindn/log/nlsr.log

**Comment by whiteysy** [comment]
Thanks for your reply! I knew nlsrc and used it before. Is there some other commands expect ndn-tools and the help hin? Like nfdc......or i can find it in some documents?

**Comment by whiteysy** [comment]
Thanks for your reply! I knew nlsrc and used it before. Is there some other commands expect ndn-tools and the help hint? Like nfdc......or i can find it in some documents?

**Comment by whiteysy** [comment]
OK, i will try it. Appreciated your reply so quickly!

**Comment by whiteysy** [comment]
Hi, where is the emulator start file stored at? I find that NLSR soure code is stored at '/minindn/NLSR/src' and it uses c++. But there is nlsr.py at 'minindn/ndn'. How do they work together? By 'minindn/pyNDN2' to invoke the c++ files?

**Comment by whiteysy** [comment]
Thanks for your reply！But I still don’t understand how nlsr.py runs the binary. Are there some sentences in nlsr.py about this? Can I think the NLSR binary is like a software and nlsr.py can use it directly?

**Comment by agawande** [comment]
Yes, https://github.com/named-data/mini-ndn/blob/master/ndn/nlsr.py#L56

**Comment by whiteysy** [comment]
Thanks!
