### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by whiteysy** [named-data/mini-ndn#35]
Hi,
Does NLSR sends/receives packets to/from NFD by unix domain socket? How does NFD handle these packets when it receives packets from NLSR or other applications. It still put them in forwarding pipelines as usual? And how does NFD handle these packets when it receives interest/data produced by neighbor's NLSR?   
Look forward to your reply.

**Comment by agawande** [comment]
Yes using unix socket by default (or as configured in https://github.com/named-data/ndn-cxx/blob/master/client.conf.sample). Yes, still puts them on forwarding pipelines. NFD forwards them to the prefixes NLSR is listening on.

**Comment by whiteysy** [comment]
Thanks for your reply. I still have some questions. When NFD receives packets produced by neighbor's NLSR, how does it recognize if packets are from NLSR? By some filters, or some callback functions? How does NFD transport neighbor's NLSR packets from the received face to unix socket when it receives neighbor's NLSR packets?

**Comment by whiteysy** [comment]
I think it uses ndn-cxx's face and nlsr's fib to register NFD's route entry in advance to implement listening NLSR's prefix.
