### ISSUE TITLE
ndn-tools build failed

### ISSUE THREAD

**Issue by Zakaria55** [named-data/mini-ndn#41]
Hi,

I have a problem with the build of ndn-tools. The command "./waf configure" ran successfully, but the next command "./waf" doesn't. I have always errors:
`
zakaria@ubuntu:~/mini-ndn/ndn-tools$ sudo ./waf configure
Setting top to                           : /home/zakaria/mini-ndn/ndn-tools 
Setting out to                           : /home/zakaria/mini-ndn/ndn-tools/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking C++ compiler version            : 5.4.0 
Checking supported CXXFLAGS              : -std=c++14 
Checking supported LINKFLAGS             : -fuse-ld=gold 
Checking for program 'sphinx-build'      : /usr/local/bin/sphinx-build 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'libndn-cxx'                : yes 
Checking for program 'dpkg-architecture' : /usr/bin/dpkg-architecture 
Checking boost includes                  : 1.58.0 
Checking boost libs                      : boost_system boost_program_options boost_filesystem 
Checking for boost linkage               : ok 
Checking for 'libpcap'                   : yes 
Checking if struct tcphdr has member th_off  : yes 
Checking if struct udphdr has member uh_ulen : yes 
Checking supported CXXFLAGS                  : -O2 -g -pedantic -Wall -Wextra -Wnon-virtual-dtor -Wno-unused-parameter -fdiagnostics-color 
Checking supported LINKFLAGS                 : -Wl,-O1 
Tools to build                               : peek, dump, dissect, ping, chunks, dissect-wireshark 
'configure' finished successfully (1.088s)
zakaria@ubuntu:~/mini-ndn/ndn-tools$ sudo ./waf
Waf: Entering directory `/home/zakaria/mini-ndn/ndn-tools/build'
[ 5/39] Linking build/bin/ndnpeek
[ 8/39] Linking build/bin/ndnpoke
[19/39] Linking build/bin/ndnping
../tools/peek/ndnpeek/ndnpeek.hpp:61: error: undefined reference to 'ndn::scheduler::Scheduler::~Scheduler()'
../tools/peek/ndnpeek/main.cpp:182: error: undefined reference to 'ndn::io::loadBuffer(std::istream&, ndn::io::IoEncoding)'
../tools/peek/ndnpeek/main.cpp:197: error: undefined reference to 'ndn::io::loadBuffer(std::istream&, ndn::io::IoEncoding)'
../tools/peek/ndnpeek/ndnpeek.cpp:38: error: undefined reference to 'ndn::scheduler::Scheduler::Scheduler(boost::asio::io_service&)'
../tools/peek/ndnpeek/ndnpeek.cpp:70: error: undefined reference to 'ndn::Interest::setHopLimit(nonstd::optional_lite::optional<unsigned char>)'
../tools/peek/ndnpeek/ndnpeek.cpp:51: error: undefined reference to 'ndn::scheduler::Scheduler::schedule(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> >, std::function<void ()>)'
collect2: error: ld returned 1 exit status

../tools/peek/ndnpoke/ndnpoke.hpp:56: error: undefined reference to 'ndn::scheduler::Scheduler::~Scheduler()'
../tools/peek/ndnpoke/ndnpoke.cpp:114: error: undefined reference to 'ndn::scheduler::Scheduler::schedule(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> >, std::function<void ()>)'
../tools/peek/ndnpoke/ndnpoke.cpp:41: error: undefined reference to 'ndn::scheduler::Scheduler::Scheduler(boost::asio::io_service&)'
collect2: error: ld returned 1 exit status

../tools/ping/client/ping.hpp:54: error: undefined reference to 'ndn::scheduler::Scheduler::~Scheduler()'
../tools/ping/client/ping.cpp:77: error: undefined reference to 'ndn::scheduler::Scheduler::schedule(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> >, std::function<void ()>)'
../tools/ping/client/ping.cpp:37: error: undefined reference to 'ndn::scheduler::Scheduler::Scheduler(boost::asio::io_service&)'
../tools/ping/client/ping.cpp:37: error: undefined reference to 'ndn::scheduler::Scheduler::~Scheduler()'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/zakaria/mini-ndn/ndn-tools/build'
Build failed
 -> task in 'ndnpeek' failed with exit status 1 (run with -v to display more information)
 -> task in 'ndnpoke' failed with exit status 1 (run with -v to display more information)
 -> task in 'ndnping' failed with exit status 1 (run with -v to display more information)
`

Could you help me, please?
Thanks in advance.

**Comment by agawande** [comment]
Need more info on how ndn-cxx is installed - source or PPA? And what are the commit version for ndn-cxx and ndn-tools?

**Comment by Zakaria55** [comment]
> Need more info on how ndn-cxx is installed - source or PPA? And what are the commit version for ndn-cxx and ndn-tools?

Thanks for your reply. In fact, it's my first time installing mini-ndn, so I am following the tutorial in the official website (http://minindn.memphis.edu/mini_ndn_installation.php)

**Comment by agawande** [comment]
ldconfig -p | grep "boost\|ndn-cxx"?

From the tutorial are you following the -a or are you installing each one manually?
If manually how did you install NFD? From apt or from source - these cannot be mixed and matched.

**Comment by Zakaria55** [comment]
> ldconfig -p | grep "boost\|ndn-cxx"?
> 
> From the tutorial are you following the -a or are you installing each one manually?
> If manually how did you install NFD? From apt or from source - these cannot be mixed and matched.

zakaria@ubuntu:~/mini-ndn/ndn-tools$ **ldconfig -p | grep "boost\|ndn-cxx"**
	libndn-cxx.so.0.6.6 (libc6,x86-64) => /usr/local/lib/libndn-cxx.so.0.6.6
	libndn-cxx.so.0.6.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libndn-cxx.so.0.6.6
	libndn-cxx.so (libc6,x86-64) => /usr/local/lib/libndn-cxx.so
	libndn-cxx.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libndn-cxx.so
	libboost_wserialization.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_wserialization.so.1.58.0
	libboost_wserialization.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_wserialization.so
	libboost_wave.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_wave.so.1.58.0
	libboost_wave.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_wave.so
	libboost_unit_test_framework.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.58.0
	libboost_unit_test_framework.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so
	libboost_timer.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_timer.so.1.58.0
	libboost_timer.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_timer.so
	libboost_thread.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
	libboost_thread.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_thread.so
	libboost_system.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
	libboost_system.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_system.so
	libboost_signals.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_signals.so.1.58.0
	libboost_signals.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_signals.so
	libboost_serialization.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.58.0
	libboost_serialization.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_serialization.so
	libboost_regex.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0
	libboost_regex.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_regex.so
	libboost_random.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_random.so.1.58.0
	libboost_random.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_random.so
	libboost_python-py35.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
	libboost_python-py35.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
	libboost_python-py27.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
	libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
	libboost_program_options.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0
	libboost_program_options.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_program_options.so
	libboost_prg_exec_monitor.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so.1.58.0
	libboost_prg_exec_monitor.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so
	libboost_mpi_python-py35.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.so.1.58.0
	libboost_mpi_python-py35.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.so
	libboost_mpi_python-py27.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.so.1.58.0
	libboost_mpi_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.so
	libboost_mpi.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.58.0
	libboost_mpi.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_mpi.so
	libboost_math_tr1l.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so.1.58.0
	libboost_math_tr1l.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so
	libboost_math_tr1f.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so.1.58.0
	libboost_math_tr1f.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so
	libboost_math_tr1.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_tr1.so.1.58.0
	libboost_math_tr1.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_tr1.so
	libboost_math_c99l.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_c99l.so.1.58.0
	libboost_math_c99l.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_c99l.so
	libboost_math_c99f.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_c99f.so.1.58.0
	libboost_math_c99f.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_c99f.so
	libboost_math_c99.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_c99.so.1.58.0
	libboost_math_c99.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_math_c99.so
	libboost_log_setup.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_log_setup.so.1.58.0
	libboost_log_setup.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_log_setup.so
	libboost_log.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0
	libboost_log.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_log.so
	libboost_locale.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_locale.so.1.58.0
	libboost_locale.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_locale.so
	libboost_iostreams.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
	libboost_iostreams.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_iostreams.so
	libboost_graph_parallel.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so.1.58.0
	libboost_graph_parallel.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so
	libboost_graph.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_graph.so.1.58.0
	libboost_graph.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_graph.so
	libboost_filesystem.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
	libboost_filesystem.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
	libboost_date_time.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.58.0
	libboost_date_time.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_date_time.so
	libboost_coroutine.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_coroutine.so.1.58.0
	libboost_coroutine.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_coroutine.so
	libboost_context.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_context.so.1.58.0
	libboost_context.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_context.so
	libboost_chrono.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
	libboost_chrono.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_chrono.so
	libboost_atomic.so.1.58.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.58.0
	libboost_atomic.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_atomic.so

From the tutorial, I followed the -a but it seems like it doesn't install all the dependencies, so I installed them one by one manually, and I found the mentioned error in ndn-tools.

Concerning the NFD, I think that I have mixed the apt and the source! I thought that I have to run all the commands cited on this page: https://named-data.net/doc/NFD/current/INSTALL.html
Is it the cause of the error?

**Comment by agawande** [comment]
Yes mixing is the problem. I think documentation needs to clarify that and will be updated in near future. Which dependencies did -a miss? It would be good to know what failed with -a.

You can remove NFD from apt:
sudo apt remove --purge nfd
sudo apt autoremove

and make sure ndn-cxx-0.6.6 does not show up in ldconfig output.

Then reinstall (./waf && sudo ./waf install) ndn-cxx, NFD, NLSR, ndn-tools by going in to each directory cloned by Mini-NDN in the mini-ndn folder.

Alternatively install ndn-tools from apt if you want to use the release version instead of the latest.

**Comment by Zakaria55** [comment]
> Yes mixing is the problem. I think documentation needs to clarify that and will be updated in near future. Which dependencies did -a miss? It would be good to know what failed with -a.
> 
> You can remove NFD from apt:
> sudo apt remove --purge nfd
> sudo apt autoremove
> 
> and make sure ndn-cxx-0.6.6 does not show up in ldconfig output.
> 
> Then reinstall (./waf && sudo ./waf install) ndn-cxx, NFD, NLSR, ndn-tools by going in to each directory cloned by Mini-NDN in the mini-ndn folder.
> 
> Alternatively install ndn-tools from apt if you want to use the release version instead of the latest.

Okay, I'll try this. Thanks a lot sir.
