### ISSUE TITLE
Vagrant up hangs due to APT requesting user interaction

### ISSUE THREAD

**Issue by GiovanniGrieco** [named-data/mini-ndn#42]
Due to a recent update of a package dependency, `vagrant up` now hangs because APT waits for user input to the following question:
> Configuring wireshark-common
> Dumpcap can be installed in a way that allows members of the "wireshark" system group to capture packets. This is recommended over the alternative of running Wireshark/Tshark directly as root, because less of the code will run with elevated privileges. For more detailed information please see /usr/share/doc/wireshark common/README.Debian. Enabling this feature may be a security risk, so it is disabled by default. If in doubt, it is suggested to leave it disabled. Should non-superusers be able to capture packets?
> [Yes] [No]

This question is raised during Open vSwitch setup procedure.

Unfortunately, I am not able to override the APT behaviour. I've tried to use `DEBIAN_FRONTEND=noninteractive` in both `Vagrantfile` and `install.sh`. I've also tried, unsuccessfully, to issue a `sudo dpkg-reconfigure debconf -f noninteractive -p critical` prior to Vagrant provision.

Is there any way to force a fully unattended installation using Vagrant?

**Comment by agawande** [comment]
This seems to work for me:

```
diff --git a/install.sh b/install.sh
index 0fbb689..d1b8cfd 100755
--- a/install.sh
+++ b/install.sh
@@ -191,9 +191,6 @@ function infoedit {
 }
 
 function minindn {
-    $install libigraph0-dev tshark
-    sudo pip install -r requirements.txt
-
     if [[ updated != true ]]; then
         if [ ! -d "build" ]; then
             $update
@@ -201,6 +198,14 @@ function minindn {
         fi
     fi
 
+    $install libigraph0-dev
+    echo "wireshark-common wireshark-common/install-setuid boolean false" | sudo debconf-set-selections
+    DEBIAN_FRONTEND=noninteractive
+    $install tshark
+    unset DEBIAN_FRONTEND
+
+    sudo pip install -r requirements.txt
+
```

**Comment by GiovanniGrieco** [comment]
Yes it works. 
Wouldn't be better to specify this behavior on `Vagrantfile`? This way we prevent any further issues on Vagrant in case of future questions during package installation.
