### ISSUE TITLE
ERROR: No default identity

### ISSUE THREAD

**Issue by WangwzZB** [named-data/mini-ndn#48]
When I run the pingall.py and any other experiment, it shows that:

> root@ubuntu:~/mini-ndn-demo/mini-ndn# sudo python examples/nlsr/pingall.py
Using topology file /usr/local/etc/mini-ndn/default-topology.conf
*** Creating network
*** Adding controller
*** Adding hosts:
a b c d 
*** Adding switches:

*** Adding links:
(10ms delay) (10ms delay) (a, b) (10ms delay) (10ms delay) (a, c) (10ms delay) (10ms delay) (b, d) 
*** Configuring hosts
a b c d 
ERROR: No default identity
*** Starting controller
c0 
*** Starting 0 switches

Waiting 60 seconds for convergence...
...done
NLSR has converged successfully.
Each node will ping 4 node(s)
Scheduling ping(s) from a to b
Scheduling ping(s) from a to c
Scheduling ping(s) from a to d
Scheduling ping(s) from b to c
Scheduling ping(s) from b to d
Scheduling ping(s) from b to a
Scheduling ping(s) from c to d
Scheduling ping(s) from c to a
Scheduling ping(s) from c to b
Scheduling ping(s) from d to a
Scheduling ping(s) from d to b
Scheduling ping(s) from d to c
*** Starting CLI:
mini-ndn> 

So why does it tell me," No default identity”. Is there something I forgot to install?

**Comment by dulalsaurab** [comment]
If you install dummy key chain patch, this message will go away. We brought dummy keychan from ndnsim make experiments faster and scale. Installing dummy-key chain is optional and won't cause any problem. It comes from the following line: https://github.com/named-data/mini-ndn/blob/master/minindn/minindn.py#L99 which checks if the dummy key chain is installed in the system or not. And if it's not, and also if there is no default identity installed in the system you get that message. We will suppress the message in some later patch. Thanks for pointing out.

**Comment by WangwzZB** [comment]
Thank you！ I try to apply the ndn-cxx-dummy-keychain-from-ndnsim.patch, but that failed. Then I find that I just install the latest version of ndn-cxx which was realeased on 14 Jan and not suit the  ndn-cxx-dummy-keychain-from-ndnsim.patch, so I think  a update is needed. Thanks for your working!

**Comment by WangwzZB** [comment]
Thank you！ I try to apply the ndn-cxx-dummy-keychain-from-ndnsim.patch, but that failed. Then I find that I just install the latest version of ndn-cxx(0.7.0 )which was realeased on 14 Jan and not suit the ndn-cxx-dummy-keychain-from-ndnsim.patch, so I think a update is needed. Thanks for your working!

**Comment by agawande** [comment]
Yes, patch is old. Can you please test https://gerrit.named-data.net/c/mini-ndn/+/6175
@awlane

**Comment by WangwzZB** [comment]
I test the new patch. No error shows, but it still not work. 
```
root@ecs-b437:~/mini-ndn/mini-ndn# git -C ndn-src/ndn-cxx/ apply /root/mini-ndn/mini-ndn/patches/ndn-cxx-dummy-keychain-from-ndnsim.patch
root@ecs-b437:~/mini-ndn/mini-ndn# sudo python examples/nlsr/pingall.py
Using topology file /usr/local/etc/mini-ndn/default-topology.conf
*** Creating network
*** Adding controller
*** Adding hosts:
a b c d
*** Adding switches:

*** Adding links:
(10ms delay) (10ms delay) (a, b) (10ms delay) (10ms delay) (a, c) (10ms delay) (10ms delay) (b, d)
*** Configuring hosts
a b c d
ERROR: No default identity
*** Starting controller
c0
*** Starting 0 switchese
```

**Comment by WangwzZB** [comment]
I apply the new patch, and no errors shows.
```
root@ecs-b437:~/mini-ndn/mini-ndn# git -C ndn-src/ndn-cxx/ apply /root/mini-ndn/mini-ndn/patches/ndn-cxx-dummy-keychain-from-ndnsim.patch
```
But when I want to reinstall the ndn-cxx, the flowing errors spring up.
```
root@ecs-b437:~/mini-ndn/mini-ndn/ndn-src/ndn-cxx# ./waf -v
Waf: Entering directory `/root/mini-ndn/mini-ndn/ndn-src/ndn-cxx/build'
[185/205] Linking build/bin/ndnsec
13:58:08 runner ['/usr/bin/g++', '-Wl,-O1', '-fuse-ld=gold', '-pthread', 'tools/ndnsec/main.cpp.2.o', 'tools/ndnsec/cert-dump.cpp.1.o', 'tools/ndnsec/cert-gen.cpp.1.o', 'tools/ndnsec/cert-install.cpp.1.o', 'tools/ndnsec/delete.cpp.1.o', 'tools/ndnsec/export.cpp.1.o', 'tools/ndnsec/get-default.cpp.1.o', 'tools/ndnsec/import.cpp.1.o', 'tools/ndnsec/key-gen.cpp.1.o', 'tools/ndnsec/list.cpp.1.o', 'tools/ndnsec/set-default.cpp.1.o', 'tools/ndnsec/sign-req.cpp.1.o', 'tools/ndnsec/unlock-tpm.cpp.1.o', 'tools/ndnsec/util.cpp.1.o', '-o/root/mini-ndn/mini-ndn/ndn-src/ndn-cxx/build/bin/ndnsec', '-Wl,-Bstatic', '-L.', '-L/usr/lib/x86_64-linux-gnu', '-Wl,-Bdynamic', '-L.', '-L/usr/lib/x86_64-linux-gnu', '-L/usr/lib', '-lndn-cxx', '-lboost_system', '-lboost_program_options', '-lboost_chrono', '-lboost_date_time', '-lboost_filesystem', '-lboost_thread', '-lboost_log', '-lboost_stacktrace_backtrace', '-lcrypto', '-lsqlite3', '-latomic', '-lrt', '-lpthread']
./libndn-cxx.so: error: undefined reference to 'EVP_sha3_512'
./libndn-cxx.so: error: undefined reference to 'EVP_blake2b512'
./libndn-cxx.so: error: undefined reference to 'EVP_blake2s256'
./libndn-cxx.so: error: undefined reference to 'EVP_sha3_224'
./libndn-cxx.so: error: undefined reference to 'EVP_sha3_256'
./libndn-cxx.so: error: undefined reference to 'EVP_sha3_384'
./libndn-cxx.so: error: undefined reference to 'EVP_MD_CTX_free'
./libndn-cxx.so: error: undefined reference to 'EVP_MD_CTX_new'
./libndn-cxx.so: error: undefined reference to 'EVP_PKEY_get_raw_private_key'
./libndn-cxx.so: error: undefined reference to 'RSA_pkey_ctx_ctrl'
./libndn-cxx.so: error: undefined reference to 'EVP_PKEY_new_raw_private_key'
./libndn-cxx.so: error: undefined reference to 'EVP_PKEY_get0_hmac'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/root/mini-ndn/mini-ndn/ndn-src/ndn-cxx/build'
Build failed
 -> task in 'tool-ndnsec' failed with exit status 1:
        {task 139695924940872: cxxprogram main.cpp.2.o,cert-dump.cpp.1.o,cert-gen.cpp.1.o,cert-install.cpp.1.o,delete.cpp.1.o,export.cpp.1.o,get-default.cpp.1.o,import.cpp.1.o,key-gen.cpp.1.o,list.cpp.1.o,set-default.cpp.1.o,sign-req.cpp.1.o,unlock-tpm.cpp.1.o,util.cpp.1.o -> ndnsec}
['/usr/bin/g++', '-Wl,-O1', '-fuse-ld=gold', '-pthread', 'tools/ndnsec/main.cpp.2.o', 'tools/ndnsec/cert-dump.cpp.1.o', 'tools/ndnsec/cert-gen.cpp.1.o', 'tools/ndnsec/cert-install.cpp.1.o', 'tools/ndnsec/delete.cpp.1.o', 'tools/ndnsec/export.cpp.1.o', 'tools/ndnsec/get-default.cpp.1.o', 'tools/ndnsec/import.cpp.1.o', 'tools/ndnsec/key-gen.cpp.1.o', 'tools/ndnsec/list.cpp.1.o', 'tools/ndnsec/set-default.cpp.1.o', 'tools/ndnsec/sign-req.cpp.1.o', 'tools/ndnsec/unlock-tpm.cpp.1.o', 'tools/ndnsec/util.cpp.1.o', '-o/root/mini-ndn/mini-ndn/ndn-src/ndn-cxx/build/bin/ndnsec', '-Wl,-Bstatic', '-L.', '-L/usr/lib/x86_64-linux-gnu', '-Wl,-Bdynamic', '-L.', '-L/usr/lib/x86_64-linux-gnu', '-L/usr/lib', '-lndn-cxx', '-lboost_system', '-lboost_program_options', '-lboost_chrono', '-lboost_date_time', '-lboost_filesystem', '-lboost_thread', '-lboost_log', '-lboost_stacktrace_backtrace', '-lcrypto', '-lsqlite3', '-latomic', '-lrt', '-lpthread']
```

**Comment by agawande** [comment]
Can you try ./waf distclean && ./waf configure && ./waf in ndn-cxx?
Also this is latest ndn-cxx github master right?

**Comment by WangwzZB** [comment]
Thanks.  I install successfully, and It  shows，`Security will be disabled`.  What does that means,?  How to make the node creat with Security?
```
root@ecs-b437:~/mini-ndn/mini-ndn# sudo python examples/mnndn.py
Using topology file /usr/local/etc/mini-ndn/default-topology.conf
*** Creating network
*** Adding controller
*** Adding hosts:
a b c d
*** Adding switches:

*** Adding links:
(10ms delay) (10ms delay) (a, b) (10ms delay) (10ms delay) (a, c) (10ms delay) (10ms delay) (b, d)
*** Configuring hosts
a b c d
Dummy key chain patch is installed in ndn-cxx. Security will be disabled.
*** Starting controller
c0
*** Starting 0 switches

Starting NFD on nodes
Starting NLSR on nodes
*** Starting CLI:
```

**Comment by agawande** [comment]
Yes, that patch disables security in ndn-cxx. Remove the patch if you want security enabled.

It will (still) give you the no default identity error - but you can ignore that (we will suppress that in some other change soon as Saurab mentioned).

**Comment by WangwzZB** [comment]
Thank you！
