### ISSUE TITLE
Install Verification Steps Need Updating

### ISSUE THREAD

**Issue by alexvoss** [named-data/mini-ndn#5]
Hi,

I installed mini-ndn but am getting this error in the verification step:

--8<--
vagrant@vagrant-ubuntu-trusty-64:~$ sudo minindn --pingall 50 --ctime 180 ndn_utils/hyperbolic_conf_file/minindn.caida.conf
Usage: minindn [template_file] [ -t | --testbed ]
    If no template_file is given, ndn_utils/default-topology.conf (given sample file)
    will be used.
    If --testbed is used, minindn will run the NDN Project Testbed.

minindn: error: no such option: --pingall
--8<--

It seems the command-line options have changed. Not sure if I should replace --pingall with -nPings?

Cheers,

Alex

**Comment by alexvoss** [comment]
I am sorry, I realise I should say how I installed this. I am running mini-ndn in Vagrant (https://www.vagrantup.com/) using the files attached.

[Vagrantfile.txt](https://github.com/named-data/mini-ndn/files/138131/Vagrantfile.txt)
[bootstrap.sh.txt](https://github.com/named-data/mini-ndn/files/138132/bootstrap.sh.txt)

**Comment by vslehman** [comment]
Hi Alex,

Thank you for pointing this out. The instructions in INSTALL.md are out of date and will not work with the current version of Mini-NDN.

You can use these steps to verify your installation:

1. Issue the command: `sudo minindn --experiment=pingall --nPings=50`
2. When the `mininet>` CLI prompt appears, the experiment has finished. On the Mini-NDN CLI, issue the command `exit` to exit the experiment.
3. Issue the command: `grep -c content /tmp/*/ping-data/*.txt`. Each file should report a count of 50.
4. Issue the command: `grep -c timeout /tmp/*/ping-data/*.txt`. Each file should report a count of 0.

I have added this bug to our issue tracker: [http://redmine.named-data.net/issues/3467](http://redmine.named-data.net/issues/3467)
