### ISSUE TITLE
~/mini-ndn python3: can't open file './testbed_topo_generator.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Rj2014** [named-data/mini-ndn#50]
As I didn’t have the dependencies to install Mini NDN, the used following command to install them from source along with Mini-NDN.
./install.sh -a

Everything installed correctly but In the end, I received one Info stating:
~/mini-ndn
python3: can't open file './testbed_topo_generator.py': [Errno 2] No such file or directory

I have also attached the screenshot of the terminal for reference. 
How to solve this error? Where can I find the mentioned file?
![Screenshot from 2020-10-02 03-04-16](https://user-images.githubusercontent.com/36701813/94866058-45d4ac00-045c-11eb-87a2-7803f82f0786.png)

**Comment by dulalsaurab** [comment]
Thanks for reporting this. There was a small bug, we have just fixed it https://github.com/named-data/mini-ndn/commit/5dbf99dd7851b1bb3c83f5910b0078e44e8ec715. Please `git pull`, and install it `./install -i`, rest should be fine. Let us know if you encounter more issues.
