### ISSUE TITLE
Individual NFD

### ISSUE THREAD

**Issue by RafaelDBeltran** [named-data/mini-ndn#52]
How i can run in each host of mini-ndn one NFD?

Scenario: I want to close the NFD just in one host not in the others. Thats is possible?

**Comment by dulalsaurab** [comment]
> How i can run in each host of mini-ndn one NFD?

Do you want to run just one NFD for all the nodes? If so, this is not possible. Each node in Mini-NDN runs a separate instance of NFD (forwarder). This is a required condition for ndn communication.

> Scenario: I want to close the NFD just in one host not in the others. Thats is possible?

Yes, you can close NFD in one host, but then the host will not take part in ndn communication, you won't be able to transfer any ndn packets via it. 
Can you please elaborate on what is your use case, what are you trying to achieve doing this?

**Comment by RafaelDBeltran** [comment]
I am developing an experimental assessment environment for ICN. I am testing node failure cases. So I asked about the feasibility of turning off one NFD without turning off the others.

**Comment by RafaelDBeltran** [comment]
I expressed myself poorly in the first question, I wanted to say close only one NFD without closing the others in a node. In my execution all NFDs are closed when use the nfd-stop on node A for example.

**Comment by dulalsaurab** [comment]
You can do the following to stop/start nfd/nlsr in each node. 

``nlsrs[node.name].stop()``
``nfds[node.name].stop()``

``nfds[node.name].start()``
``nlsrs[node.name].start()``

don't forget to initialize nfds and nlsrs instances like here - > [https://github.com/named-data/mini-ndn/blob/master/examples/nlsr/mcn_failure.py#L80](https://github.com/named-data/mini-ndn/blob/master/examples/nlsr/mcn_failure.py#L80)

Look at the following experiments. It is doing something similar to what you are looking for. 

https://github.com/named-data/mini-ndn/blob/master/examples/nlsr/multiple_failure.py
https://github.com/named-data/mini-ndn/blob/master/examples/nlsr/mcn_failure.py#L53
