### ISSUE TITLE
mini-ndn/docs/install.rst should be updated

### ISSUE THREAD

**Issue by nikosft** [named-data/mini-ndn#56]
Install.rst instructs users to install mininet. However https://github.com/named-data/mini-ndn/blob/master/docs/install.rst#verification does not work with mininet, instead it requires mininet-wifi.

**Comment by yoursunny** [comment]
This is fixed during installation script update.
https://github.com/named-data/mini-ndn/commit/48ada89a8a39d144863002a79cc89e0aacd0a22b
