### ISSUE TITLE
Cannot unpack waf lib into a directory

### ISSUE THREAD

**Issue by Vishant02** [named-data/mini-ndn#58]
Error: Cannot unpack waf lib into /home/vagrant/mkb/mini-ndn/ndn-src/ndn-cxx/.waf3-2.0.21-16cd196b0fc7b4eebe195ce20396f3d1
Move waf in a writable directory

This is the error coming up while installing the minindn

**Comment by yoursunny** [comment]
What type of filesystem does the mentioned directory reside on?
Is it a local filesystem, or a VirtualBox shared folder?

Is the (virtual) disk full?

**Comment by Vishant02** [comment]
I got it fixed. I was using a virtualbox shared folder
