### ISSUE TITLE
the mininet cli isnt showing 

### ISSUE THREAD

**Issue by lahmer** [named-data/mini-ndn#6]
i installed the minindn successfully but when i try to start it i get this the mininet cli is'nt showing and i get this error 
`sudo minindn --experiment=pingall --nPings=50
No results folder specified; experiment results will remain in the working directory
Parse of /usr/local/etc/mini-ndn/default-topology.conf done.
**\* Creating network
**\* Adding controller
**\* Adding hosts:
a b c d 
**\* Adding switches:

**\* Adding links:
**\* gave up after 3 retries
`

**Comment by agawande** [comment]
Can you try to run mininet and see if it gets the cli?

sudo mn

How did you install Mininet? Were there any errors?

Ashlesh

On Oct 7, 2016 12:20 PM, lahmer <notifications@github.com> wrote:

i installed the minindn successfully but when i try to start it i get this the mininet cli is'nt showing and i get this error
`sudo minindn --experiment=pingall --nPings=50
No results folder specified; experiment results will remain in the working directory
Parse of /usr/local/etc/mini-ndn/default-topology.conf done.
*** Creating network
*** Adding controller
*** Adding hosts:
a b c d
*** Adding switches:

*** Adding links:
*** gave up after 3 retries
`

**Comment by lahmer** [comment]
Hi I tried to run Mininet and i got the same problem.

> How did you install Mininet? Were there any errors?

i installed it using   sudo ./install.sh -mrfti  and there were no errors everything went fine

**Comment by agawande** [comment]
Can you go to your Mininet folder and run sudo ./util/install.sh -nv
and see if there are any errors?

Also can you please tell your OS details?

**Comment by Ilka2002** [comment]
I also installed the Mini-NDN successfully, but when I try to start with the command: 'sudo minindn --experiment=pingall --nPings=50', I get the following error: 'nfd.conf or nfd.conf.sample cannot be found in the expected directory. Exit.'. When I run the mininet it works.

**Comment by Ilka2002** [comment]
Complementing error:
'No results folder specified; experiment results will remain in the working directory
No results folder specified; experiment results will remain in the working directory'

**Comment by Ilka2002** [comment]
Complementing error:
'No results folder specified; experiment results will remain in the working directory
nfd.conf or nfd.conf.sample cannot be found in the expected directory. Exit.'

**Comment by agawande** [comment]
Did you install NFD (and all the other dependencies)?
If so then there should nfd.conf.sample in /usr/local/etc/ndn
(If you installed from package - that is currently not supported)

**Comment by Ilka2002** [comment]
I installed from command: sudo ./install.sh -mrfti

**Comment by agawande** [comment]
May that was not successfully. Can you go into the NFD folder that should be under your mini-ndn folder and try to run sudo ./waf install?
