### ISSUE TITLE
install third-party lib

### ISSUE THREAD

**Issue by freeshman1996** [named-data/mini-ndn#63]
I don't konw how to install third-party lib,such as NAC-ABE.Can you give me some guidances.

**Comment by dulalsaurab** [comment]
Please follow the instructions here: https://github.com/UCLA-IRL/NAC-ABE

**Comment by freeshman1996** [comment]
I want to know how to use the third-party lib with minindn. I have installed NACabe on my computer. ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月21日(星期五) 凌晨1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [named-data/mini-ndn] install third-party lib (#63)

**Comment by dulalsaurab** [comment]
Once you have installed the third-party lib in your system, you can use it from the experiment. Refer to this example: https://gerrit.named-data.net/c/mini-ndn/+/6426/10/examples/chunks.py#36 . It shows the use of [catchunks](https://github.com/named-data/ndn-tools/tree/master/tools/chunks) (file transfer)

Also, we are improving our documentation and are also including some examples to demonstrate the use of third-part lib. I will soon be in the repo and the [minindn website](www.minindn.memphis.edu)

**Comment by dulalsaurab** [comment]
Addressed in [86c914](https://github.com/named-data/mini-ndn/commit/20855447994edd463963438f30e7bfc2c286c914)
