### ISSUE TITLE
help i am new to ndn

### ISSUE THREAD

**Issue by lahmer** [named-data/mini-ndn#7]
i know this is not the right place to post such a request but i didnt got help elsewhere. I am new to NDN and I am planning to get started with Ndn . i have an idea of a protocole for ndn archetecture and i dont know the best way to use the tools provided from the community to implement it and possibly compare it with other protocoles. plzz help

**Comment by agawande** [comment]
Can you go to your Mininet folder and run sudo ./util/install.sh -nv
and see if there are any errors?

Also can you please tell your OS details?
