### ISSUE TITLE
default NFD log-level set to NONE 

### ISSUE THREAD

**Issue by signorello** [named-data/mini-ndn#8]
Dear devs,
I have realized that the default value for NFD's log-level is set to NONE (source file nfd.py). I wonder if this is a good choice. In fact, I would have expected to have sth logged (INFO level) at least.
In addition to that, I would indicate in the docs/CONFIG.md that the log-level can be changed in the Configuration file with the attribute "nfd-log-level" in the [nodes] section. Otherwise, users may need some time to figure out if such an attribute/parameter exists.

As always, thank you for your commitment,
Salvatore

P.S. I haven't filled a Pull request, since the changes are minimal.

**Comment by dulalsaurab** [comment]
Thank you for your feedback. More details on how to set up appropriate log levels can be found here: https://github.com/named-data/mini-ndn/blob/master/docs/experiment.rst

PS: We will see what we can do to make this easier/clear in our next release.
