### ISSUE TITLE
cant start nfd from minindn host 

### ISSUE THREAD

**Issue by lahmer** [named-data/mini-ndn#9]
I am trying to start nfd from a host in mini-ndn but i am getting an error about a certificate not found 

`1476225300.296038 FATAL: [NFD] cannot load certfile /tmp/h1/certs/localhost_daemons_nfd.ndncert for authorize[0] [from ../daemon/mgmt/command-authenticator.cpp:105 in void nfd::CommandAuthenticator::processConfig(const ConfigSection&, bool, const string&)]
1476225637.804749 FATAL: [NFD] cannot load certfile /tmp/h1/certs/localhost_daemons_nfd.ndncert for authorize[0] [from ../daemon/mgmt/command-authenticator.cpp:105 in void nfd::CommandAuthenticator::processConfig(const ConfigSection&, bool, const string&)]`

**Comment by agawande** [comment]
Please install ndn-cxx, NFD, NLSR, and-ndn-tools from source. Mini-NDN is not configured to be used with PPAs as of yet (MAKE SURE TO COMPLETELY REMOVE THE PPAs FIRST!).
